# Generated by Django 3.2.9 on 2022-10-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventsponser_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='eventjobcategorylinking',
            name='job_category',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
