# Generated by Django 3.2.9 on 2022-10-16 13:53

from django.db import migrations, models
import django_admin_geomap


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20221006_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
        migrations.RemoveField(
            model_name='event',
            name='uid',
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(choices=[('River CleanUp', 'River CleanUp'), ('Street CleanUp', 'Street CleanUp'), ('Park CleanUp', 'Park CleanUp'), ('Blood Donation', 'Blood Donation'), ('Food Donation', 'Food Donation'), ('Money Donation', 'Money Donation'), ('Cloth Donation', 'Cloth Donation'), ('Climate Change', 'Climate Change'), ('Animal Rescue', 'Animal Rescue'), ('WildLife Conservation', 'WildLife Conservation'), ('Teaching', 'Teaching'), ('Counselling', 'Counselling')], max_length=70),
        ),
        migrations.DeleteModel(
            name='EventJobCategoryLinking',
        ),
    ]
